services:
  glpi:
    depends_on:
      - mysql
    build:
      context: .
    environment:
      DB_HOST: mysql
      DB_NAME: glpi
      DB_USER: glpi
      DB_PASSWORD: glpi
    ports:
      - "80:80"
  mysql:
    restart: always
    image: mysql:8.4
    volumes:
      - ./data/db/:/var/lib/mysql
      - ./data/dbdump/:/dbdump
    command: ["--mysql-native-password=ON", "--innodb_strict_mode=0"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    # ports:
    #   - 3307:3306
